// os.runApp(callback) - runs the callback application

create a callback function that:

* creates a root dom element with the class `gmroot`
* generate a matrix of 8x8 with values 0
* pick a random of 10 cells and set their value to -100 and increase the number value of the neighbouring cells
* set score to 64
* add a div with the class `score` and the content `Discovered: 64` to the root dom element
* iterate through the matrix and for each row add a div element with the class `.row` and for each item add a div with the class `cell`,  ` ` as content and add data-x and data-y as attributes. when the div is clicked call `reveal` function for the current x and y
* define internal function reveal that:
  - get div at x and y using data-x and data-y attributes",
  - if the div is already revealed return",
  - set the div content to the value of the cell and add class `.visited` to the div",
  - if the div has am integer value smaller than 0 set the div content to `💣` and call `alert` with the message `Game Over` and the title `💣 minesweeper`",
  - else decrease the score by 1 and update the score div content to `Discovered: ${score}`",
  - if the div has an integer value of 0 call `reveal` for all the neighbouring cells",
* return root element

call existing `os.runApp` with the callback as parameter