#include run

create a myApp function that takes a win parameter:
- create a root dom element 400x300 relative position
- create a character element with 🦅 as content absolute position of 20,100 and add it to the root element
- set a gravity variable with value of 2
- on each animation frame:
  - increase gravity with 0.05
  - update character position with gravity
  - if the user hits space key set gravity to -3
  - if the current top is larger than 300 then set current top to 100 and gravity to 2
- return root dom element